### PR TITLE
1.6.2 bugfixes

### PR DESCRIPTION
**Pull request by cynicaloptimist**

### CODE REVIEW

**Comment by ascendedguard** [comment]
Looks like the latest `development` branch has hotkeys broken.

**Comment by cynicaloptimist** [comment]
Are you sure about that? The hotkeys seem to work fine for me with their default configuration. Which hotkey setting is not working?

**Comment by ascendedguard** [comment]
@cynicaloptimist Looks like master was broken for me before your merge too...

None of the hotkeys are currently working, I typically use j/k and n/alt+n. Right now for me, it's not working on either master (before your merge) or development, and it's broken on the Herokuapp page but not in production, and its consistent between Chrome and Firefox.

If I get a chance, I'll try to dig into it tomorrow and see if I can figure out what's going on. If you're not seeing it, it might be something on my end.

**Comment by cynicaloptimist** [comment]
Ok, I went ahead and deployed this since it didn't repro from my end. Let me know what you find out, thanks very much for the heads up!

**Pull request merged**
