### PR TITLE
Add basic Docker support

### PR DESCRIPTION
**Pull request by dprothero**
I'm setting up a Dockerfile for my own local development environment. Any interest in having this merged in? I could add some docs to the README to show how to run it with Docker and add a docker-compose configuration to start it up with a running mongo server.

### CODE REVIEW

**Comment by cynicaloptimist** [comment]
I'd be open to this, but I don't want to have to troubleshoot it if it breaks. Are you volunteering to handle issues on it? :-)

**Comment by dprothero** [comment]
Sure! :-)

**Comment by dprothero** [comment]
OK, this should be ready to take a look at @cynicaloptimist

**Comment by cynicaloptimist** [comment]
Excellent contribution, thanks David!

**Pull request merged**
